groovy

@Library('my-ansible-library') _

node {
    // Load configuration
    def config = load "vars/config.groovy"

    // Steps using shared library functions
    clone(config.CODE_BASE_PATH, "destination-folder")
    
    // Require user approval
    userApproval("Please approve this build")

    // Execute Ansible playbook
    executePlaybook("playbooks/main.yml")

    // Send notification
    sendNotification(config.SLACK_CHANNEL_NAME, config.ENVIRONMENT, config.ACTION_MESSAGE)
}